name: Check
on:
  push
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17.0
      - name: Check scalafmtCheck
        run: sbt scalafmtCheckAll scalafmtSbtCheck
