name: Check
on:
  push
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Scalafmt
        uses: coursier/setup-action@v1.1.2
        with:
          jvm: zulu:17.0.0
      - name: Check scalafmtCheck
        run: sbt scalafmtCheckAll scalafmtSbtCheck
